/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BD.AlquilerInterfaz;

import BD.AlquilerCasas.Clases.Cliente;
import BD.AlquilerCasas.Clases.Validaciones;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author USER
 */
public class CRUD_Clientes extends javax.swing.JPanel {

    public static ArrayList<Cliente> mipersonaList = new ArrayList<>();
    char GeneroPersona;
    boolean discapacidad;

    /**
     * Creates new form CRUD_Clientes
     */
    public CRUD_Clientes() {
        initComponents();
        CargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrupSexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnH = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        btnM = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cbboxNacionalidad = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jDnacimiento = new com.toedter.calendar.JDateChooser();
        btningresar = new javax.swing.JButton();
        btnconsul = new javax.swing.JButton();
        btnmod = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersona = new javax.swing.JTable();
        btnreport = new javax.swing.JButton();
        SpinnerEdad = new javax.swing.JSpinner();
        txtcelu = new javax.swing.JTextField();
        Tfieldcedu = new javax.swing.JTextField();
        Tfieldnomb = new javax.swing.JTextField();
        Tfieldape = new javax.swing.JTextField();
        TfieldCorreo = new javax.swing.JTextField();
        btncargardatos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Cedula:");

        jLabel2.setText("Nombre:");

        jLabel6.setText("Correo:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Edad:");

        jLabel8.setText("Sexo:");

        btngrupSexo.add(btnH);
        btnH.setText("Hombre");
        btnH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHActionPerformed(evt);
            }
        });

        jLabel9.setText("Celular:");

        btngrupSexo.add(btnM);
        btnM.setText("mujer");

        jLabel5.setText("Nacionalidad:");

        cbboxNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ecuatoriano", "Mexicano", "Canadiense", "Brasileño", "Ucraniana", "Británica", "Escocesa", "Finlandesa", "Austriaca", "Rusa", "Española" }));

        jLabel12.setText("Fecha Nacimiento:");

        btningresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sav.png"))); // NOI18N
        btningresar.setText("GUARDAR");
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });

        btnconsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busqueda.png"))); // NOI18N
        btnconsul.setText("CONSULTAR");
        btnconsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsulActionPerformed(evt);
            }
        });

        btnmod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mod.png"))); // NOI18N
        btnmod.setText("MODIFICAR");
        btnmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        jTablePersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Edad", "Sexo", "Celular", "Correo", "Nacionalidad", "Fecha Nacimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePersona);

        btnreport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informe.png"))); // NOI18N
        btnreport.setText("REPORTE");
        btnreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportActionPerformed(evt);
            }
        });

        SpinnerEdad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        btncargardatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busqueda.png"))); // NOI18N
        btncargardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargardatosActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("REGISTRO DE CLIENTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tfieldape, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tfieldnomb, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnH)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnM))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(SpinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12)
                                            .addGap(18, 18, 18)
                                            .addComponent(jDnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbboxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtcelu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Tfieldcedu, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(28, 28, 28)
                                                    .addComponent(btncargardatos)
                                                    .addGap(102, 102, 102)
                                                    .addComponent(jLabel6)
                                                    .addGap(23, 23, 23)
                                                    .addComponent(TfieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btningresar)
                                .addGap(18, 18, 18)
                                .addComponent(btnconsul)
                                .addGap(18, 18, 18)
                                .addComponent(btnmod)
                                .addGap(18, 18, 18)
                                .addComponent(btneliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnreport)))
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Tfieldcedu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(btncargardatos)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(TfieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Tfieldnomb, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tfieldape, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbboxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SpinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jLabel12)
                    .addComponent(jDnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(btnH)
                        .addComponent(btnM))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcelu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btningresar)
                    .addComponent(btnconsul)
                    .addComponent(btnmod)
                    .addComponent(btneliminar)
                    .addComponent(btnreport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHActionPerformed

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        // TODO add your handling code here:

        try {
            Cliente mipersona = new Cliente();
            String cedula;
            do {
                cedula = Tfieldcedu.getText();
                if (!Validaciones.ValidarCedula(cedula)) {
                    JOptionPane.showMessageDialog(this, "Cédula incorrecta. Ingrese de nuevo");
                    return; // me regresa al formulario para ingresar de nuevo
                }
            } while (!Validaciones.ValidarCedula(cedula));
            mipersona.setCedula(cedula);

            String nombre; // varible que asigno al dato de textfield
            do {
                nombre = Tfieldnomb.getText();
                if (!Validaciones.ValidarNomApe(nombre)) {
                    JOptionPane.showMessageDialog(this, "Nombre incorrecto. Ingrese de nuevo");
                    return;
                }
            } while (!Validaciones.ValidarNomApe(nombre));
            mipersona.setNombreCliente(nombre);

            String apellido;
            do {
                apellido = Tfieldape.getText();
                if (!Validaciones.ValidarNomApe(apellido)) {
                    JOptionPane.showMessageDialog(this, "Apellido incorrecto. Ingrese de nuevo");
                    return;
                }
            } while (!Validaciones.ValidarNomApe(apellido));
            mipersona.setApellidoCliente(apellido);

            mipersona.setEdadCliente((Integer) SpinnerEdad.getValue());

            if (btnH.isSelected()) {
                GeneroPersona = 'H';
            } else if (btnM.isSelected()) {
                GeneroPersona = 'M';
            }
            mipersona.setGeneroCliente(GeneroPersona);

            String celular;
            do {
                celular = txtcelu.getText();
                if (!Validaciones.ValidarCedula(celular)) {
                    JOptionPane.showMessageDialog(this, "# Celular no valido. Ingrese de nuevo");
                    return;
                }
            } while (!Validaciones.ValidarCedula(celular));
            mipersona.setCelular(celular);

            String correo;
            do {
                correo = TfieldCorreo.getText();
                if (!Validaciones.ValidarCorreo(correo)) {
                    JOptionPane.showMessageDialog(this, "Correo no valido. Ingrese de nuevo");
                    return;
                }
            } while (!Validaciones.ValidarCorreo(correo));
            mipersona.setCorreo(correo);

            /* mipersona.setTipoSangre(cbBoxSangre.getSelectedItem().toString());

            if (CHBOXDisca.isSelected()) {
                mipersona.setDiscapacidad(true);
            } else {
                mipersona.setDiscapacidad(false);
            }*/
            mipersona.setNacionalidad((String) cbboxNacionalidad.getSelectedItem());

            // Obtener fecha de nacimiento del JCalendar
            Date fechaNacimiento = jDnacimiento.getDate();
            mipersona.setFecha_Naci(fechaNacimiento);

            mipersonaList.add(mipersona);
            JOptionPane.showMessageDialog(this, "Persona creada exitosamente");

            CargarTabla();

            Tfieldcedu.setText("");
            Tfieldnomb.setText("");
            Tfieldape.setText("");
            TfieldCorreo.setText("");
            txtcelu.setText("");
            btngrupSexo.clearSelection();

            jDnacimiento.setDate(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Los campos están vacíos");
        }
    }//GEN-LAST:event_btningresarActionPerformed

    private void btnconsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsulActionPerformed
        // TODO add your handling code here:
        boolean encontrado = false;
        if (mipersonaList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No tiene datos de personas");
        } else {
            DefaultTableModel model = (DefaultTableModel) jTablePersona.getModel();
            model.setRowCount(0); // Limpiar la tabla
            for (int i = 0; i < mipersonaList.size(); i++) {
                if (mipersonaList.get(i).getCedula().equals(Tfieldcedu.getText())) {
                    JOptionPane.showMessageDialog(this, "Si existe esa persona");
                    encontrado = true;

                    Cliente persona = mipersonaList.get(i);
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    model.addRow(new Object[]{
                        persona.getCedula(),
                        persona.getNombreCliente(),
                        persona.getApellidoCliente(),
                        persona.getEdadCliente(),
                        persona.getGeneroCliente(),
                        persona.getCelular(),
                        persona.getCorreo(),
                        persona.getNacionalidad(),
                        persona.getFecha_Naci()
                    });
                    break;//deja de buscar
                }
            }
            if (!encontrado) {
                JOptionPane.showMessageDialog(this, "No se encontro a la persona");
                CargarTabla();
            }
            Tfieldcedu.setText("");
        }
    }//GEN-LAST:event_btnconsulActionPerformed

    private void btnmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodActionPerformed
        // TODO add your handling code here:

        Cliente mipersonamod = null;
        boolean encontrado = false;

        if (mipersonaList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No tiene datos de personas");
        } else {
            for (int i = 0; i < mipersonaList.size(); i++) {
                if (mipersonaList.get(i).getCedula().equals(Tfieldcedu.getText())) {

                    encontrado = true;

                    mipersonamod = mipersonaList.get(i);

                    String nombre; // variable que asigno al dato del textfield
                    do {
                        nombre = Tfieldnomb.getText();
                        if (!Validaciones.ValidarNomApe(nombre)) {
                            JOptionPane.showMessageDialog(this, "Nombre incorrecto. Ingrese de nuevo");
                            return;
                        }
                    } while (!Validaciones.ValidarNomApe(nombre));
                    mipersonamod.setNombreCliente(nombre);

                    String apellido;
                    do {
                        apellido = Tfieldape.getText();
                        if (!Validaciones.ValidarNomApe(apellido)) {
                            JOptionPane.showMessageDialog(this, "Apellido incorrecto. Ingrese de nuevo");
                            return;
                        }
                    } while (!Validaciones.ValidarNomApe(apellido));
                    mipersonamod.setApellidoCliente(apellido);

                    mipersonamod.setEdadCliente((Integer) SpinnerEdad.getValue());

                    // Obtener el sexo seleccionado
                    char sexo = ' ';
                    if (btnH.isSelected()) {
                        sexo = 'H';
                    } else if (btnM.isSelected()) {
                        sexo = 'M';
                    }
                    mipersonamod.setGeneroCliente(sexo);

                    String celular;
                    do {
                        celular = txtcelu.getText();
                        if (!Validaciones.ValidarCedula(celular)) {
                            JOptionPane.showMessageDialog(this, "# Celular no válido. Ingrese de nuevo");
                            return;
                        }
                    } while (!Validaciones.ValidarCedula(celular));
                    mipersonamod.setCelular(celular);

                    String correo;
                    do {
                        correo = TfieldCorreo.getText();
                        if (!Validaciones.ValidarCorreo(correo)) {
                            JOptionPane.showMessageDialog(this, "Correo no válido. Ingrese de nuevo");
                            return;
                        }
                    } while (!Validaciones.ValidarCorreo(correo));
                    mipersonamod.setCorreo(correo);

                    mipersonamod.setNacionalidad((String) cbboxNacionalidad.getSelectedItem());

                    // Obtener fecha de nacimiento del JCalendar
                    Date fechaNacimiento = jDnacimiento.getDate();
                    mipersonamod.setFecha_Naci(fechaNacimiento);

                    break;
                }
            }

            if (encontrado) {
                JOptionPane.showMessageDialog(this, "Persona modificada exitosamente");
                Tfieldcedu.setEditable(true);
                btningresar.setEnabled(true);
                CargarTabla();
                Tfieldcedu.setText("");
                Tfieldnomb.setText("");
                Tfieldape.setText("");
                txtcelu.setText("");
                TfieldCorreo.setText("");
                jDnacimiento.setDate(null);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró a esa persona");

            }
        }
    }//GEN-LAST:event_btnmodActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        int removfila = jTablePersona.getSelectedRow();
        if (removfila >= 0) {
            int confirmacion = JOptionPane.showConfirmDialog(null, "Eliminar", "¿Desea eliminar el registro?", JOptionPane.YES_NO_OPTION);
            if (confirmacion == JOptionPane.YES_OPTION) {
                mipersonaList.remove(removfila);
                CargarTabla();
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportActionPerformed
        // TODO add your handling code here:
        CargarTabla();
    }//GEN-LAST:event_btnreportActionPerformed
    public void CargarTabla() {
        DefaultTableModel modelodefault = new DefaultTableModel(new String[]{"CEDULA", "NOMBRE", "APELLIDO", "EDAD", "SEXO", "CELULAR", "CORREO","NACIONALIDAD", "FECHA NACI"}, mipersonaList.size());
        jTablePersona.setModel(modelodefault);
        TableModel modeloDatos = jTablePersona.getModel();

        for (int i = 0; i < mipersonaList.size(); i++) {
            Cliente personadat = mipersonaList.get(i);
            modeloDatos.setValueAt(personadat.getCedula(), i, 0);
            modeloDatos.setValueAt(personadat.getNombreCliente(), i, 1);
            modeloDatos.setValueAt(personadat.getApellidoCliente(), i, 2);
            modeloDatos.setValueAt(personadat.getEdadCliente(), i, 3);
            modeloDatos.setValueAt(personadat.getGeneroCliente(), i, 4);
            modeloDatos.setValueAt(personadat.getCelular(), i, 5);
            modeloDatos.setValueAt(personadat.getCorreo(), i, 6);
            modeloDatos.setValueAt(personadat.getNacionalidad(), i, 7);
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String fechaNacimiento = sdf.format(personadat.getFecha_Naci()); //transformo al formato dd/mm/yyyy
            modeloDatos.setValueAt(fechaNacimiento, i, 8);

        }
    }
    private void btncargardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargardatosActionPerformed
        // TODO add your handling code here:
        btningresar.setEnabled(false);
        Tfieldcedu.setEditable(false);
        boolean encontrado = false;
        if (mipersonaList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No tiene datos de personas");
            Tfieldcedu.setEditable(true);
            btningresar.setEnabled(true);
        } else {
            for (int i = 0; i < mipersonaList.size(); i++) {
                if (mipersonaList.get(i).getCedula().equals(Tfieldcedu.getText())) {
                    JOptionPane.showMessageDialog(this, "Si existe esa persona");
                    encontrado = true;

                    Cliente personaCargar = mipersonaList.get(i);
                    Tfieldnomb.setText(personaCargar.getNombreCliente());
                    Tfieldape.setText(personaCargar.getApellidoCliente());
                    //mipersona.setEdad((Integer) SpinnerEdad.getValue());
                    // SpinnerEdad.setValue(String.valueOf((Integer) personaCargar.getEdad()));
                    SpinnerEdad.getModel().setValue(personaCargar.getEdadCliente());

                    // Cargar otros campos según corresponda
                    if (personaCargar.getGeneroCliente() == 'H') {
                        btnH.setSelected(true);
                    } else if (personaCargar.getGeneroCliente() == 'M') {
                        btnM.setSelected(true);
                    }
                    txtcelu.setText(personaCargar.getCelular());
                    TfieldCorreo.setText(personaCargar.getCorreo());

                    cbboxNacionalidad.setSelectedItem(personaCargar.getNacionalidad());
                    jDnacimiento.setDate(personaCargar.getFecha_Naci());

                    break;
                }

            }
            if (!encontrado) {
                JOptionPane.showMessageDialog(this, "No se encontro a esa persona");
                Tfieldcedu.setEditable(true);
                btningresar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btncargardatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpinnerEdad;
    private javax.swing.JTextField TfieldCorreo;
    private javax.swing.JTextField Tfieldape;
    private javax.swing.JTextField Tfieldcedu;
    private javax.swing.JTextField Tfieldnomb;
    private javax.swing.JRadioButton btnH;
    private javax.swing.JRadioButton btnM;
    private javax.swing.JButton btncargardatos;
    private javax.swing.JButton btnconsul;
    private javax.swing.JButton btneliminar;
    private javax.swing.ButtonGroup btngrupSexo;
    private javax.swing.JButton btningresar;
    private javax.swing.JButton btnmod;
    private javax.swing.JButton btnreport;
    private javax.swing.JComboBox<String> cbboxNacionalidad;
    private com.toedter.calendar.JDateChooser jDnacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePersona;
    private javax.swing.JTextField txtcelu;
    // End of variables declaration//GEN-END:variables
}
