package BD.AlquilerInterfaz;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADMIN_01
 */
public class CRUD_CasaVacacional1 extends javax.swing.JPanel {

    /**
     * Creates new form CRUD_CasaVacacional
     */
    public CRUD_CasaVacacional1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtIDCASA = new javax.swing.JTextField();
        txtIDPROPIEDAD = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        txtequipaCasa = new javax.swing.JTextField();
        txtdetallescasa = new javax.swing.JTextField();
        spnpisos = new javax.swing.JSpinner();
        spnmaximo = new javax.swing.JSpinner();
        spnhabitaciones = new javax.swing.JSpinner();
        spnbanos = new javax.swing.JSpinner();
        cboxpicina = new javax.swing.JCheckBox();
        cboxjardin = new javax.swing.JCheckBox();
        cboxwifi = new javax.swing.JCheckBox();
        cboxTV = new javax.swing.JCheckBox();
        cbxcocina = new javax.swing.JCheckBox();
        btnGUARDAR = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_casaVacacional = new javax.swing.JTable();
        cbxnacionalidad_crudcasa = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REGISTROS DE CASAS DE VACACIONES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID Casa: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ID Propiedad:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Carro:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Equipamiento de la Casa:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Numero de Pisos:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Capacidad Maxima: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Numero de Habitaciones:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Numero de Baños:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Tiene Picina:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Tiene Jardin:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Tiene WIFI:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Tiene TV:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Tiene Cocina: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Ubicacion:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Otros Detalles:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));
        jPanel1.add(txtIDCASA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 150, -1));

        txtIDPROPIEDAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDPROPIEDADActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDPROPIEDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 150, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 150, -1));
        jPanel1.add(txtequipaCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 150, -1));
        jPanel1.add(txtdetallescasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 180, -1));

        spnpisos.setModel(new javax.swing.SpinnerNumberModel(2, 1, 4, 1));
        jPanel1.add(spnpisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 60, -1));

        spnmaximo.setModel(new javax.swing.SpinnerNumberModel(5, 5, 20, 1));
        jPanel1.add(spnmaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 60, -1));

        spnhabitaciones.setModel(new javax.swing.SpinnerNumberModel(2, 2, 8, 1));
        jPanel1.add(spnhabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 60, -1));

        spnbanos.setModel(new javax.swing.SpinnerNumberModel(2, 2, 4, 1));
        jPanel1.add(spnbanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 60, -1));

        cboxpicina.setBackground(new java.awt.Color(255, 255, 255));
        cboxpicina.setForeground(new java.awt.Color(0, 0, 0));
        cboxpicina.setText("SI");
        jPanel1.add(cboxpicina, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        cboxjardin.setBackground(new java.awt.Color(255, 255, 255));
        cboxjardin.setForeground(new java.awt.Color(0, 0, 0));
        cboxjardin.setText("SI");
        jPanel1.add(cboxjardin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        cboxwifi.setBackground(new java.awt.Color(255, 255, 255));
        cboxwifi.setForeground(new java.awt.Color(0, 0, 0));
        cboxwifi.setText("SI");
        jPanel1.add(cboxwifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        cboxTV.setBackground(new java.awt.Color(255, 255, 255));
        cboxTV.setForeground(new java.awt.Color(0, 0, 0));
        cboxTV.setText("SI");
        jPanel1.add(cboxTV, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        cbxcocina.setBackground(new java.awt.Color(255, 255, 255));
        cbxcocina.setForeground(new java.awt.Color(0, 0, 0));
        cbxcocina.setText("SI");
        jPanel1.add(cbxcocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        btnGUARDAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sav.png"))); // NOI18N
        btnGUARDAR.setText("GUARDAR");
        jPanel1.add(btnGUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 120, 40));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mod.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 140, 40));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 120, 40));

        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informe.png"))); // NOI18N
        btnReporte.setText("REPORTE");
        jPanel1.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 120, 40));

        tabla_casaVacacional.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Casa", "ID Propiedad", "Carro", "Equipamiento", "Pisos", "Habitaciones", "Baños", "Picina", "Jardin", "WIFI", "TV", "Cocina", "ubicacion"
            }
        ));
        jScrollPane1.setViewportView(tabla_casaVacacional);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 800, 130));

        cbxnacionalidad_crudcasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ecuatoriano", "Mexicano", "Canadiense", "Brasileño", "Ucraniana", "Británica", "Escocesa", "Finlandesa", "Austriaca", "Rusa", "Española" }));
        jPanel1.add(cbxnacionalidad_crudcasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDPROPIEDADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDPROPIEDADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPROPIEDADActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGUARDAR;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JCheckBox cboxTV;
    private javax.swing.JCheckBox cboxjardin;
    private javax.swing.JCheckBox cboxpicina;
    private javax.swing.JCheckBox cboxwifi;
    private javax.swing.JCheckBox cbxcocina;
    private javax.swing.JComboBox<String> cbxnacionalidad_crudcasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JSpinner spnbanos;
    private javax.swing.JSpinner spnhabitaciones;
    private javax.swing.JSpinner spnmaximo;
    private javax.swing.JSpinner spnpisos;
    private javax.swing.JTable tabla_casaVacacional;
    private javax.swing.JTextField txtIDCASA;
    private javax.swing.JTextField txtIDPROPIEDAD;
    private javax.swing.JTextField txtdetallescasa;
    private javax.swing.JTextField txtequipaCasa;
    // End of variables declaration//GEN-END:variables
}
